<?php
 
$conf = array(
  'core' => array(
    'hook' => drupal_get_path('module', 'experia')  . '/hook',
    'controller' => drupal_get_path('module', 'experia')  . '/controller',
    'form' => drupal_get_path('module', 'experia')  . '/form',
    'model' => drupal_get_path('module', 'experia')  . '/model',
    'view' => drupal_get_path('module', 'experia')  . '/view',
  )                   
); 

foreach($conf['core'] as $confs_name => $conf_val){
  experia_autoloader($conf_val);
}

function experia_autoloader($path){
    if(realpath($path)){
        $fileinfos = new RecursiveIteratorIterator( new RecursiveDirectoryIterator($path) );
        if(!empty($fileinfos)){
            foreach($fileinfos as $pathname => $fileinfo) {
                if (!$fileinfo->isFile()) continue;
                if(strstr($pathname,'.php')){ // Include php files only 
                    require_once($pathname); 
                }
            }
        }
    }
}

function experia_init(){
    drupal_add_js( drupal_get_path('module', 'experia') . '/js/script.js');
    drupal_add_css( drupal_get_path('module', 'experia') . '/css/styles.css', array('group' => CSS_DEFAULT, 'type' => 'file'));
}